### ISSUE TITLE
How to remove glowbar

### ISSUE THREAD

**Issue by CharlesCoeder** [nullxception/cherry-kde-theme#4]
How can I remove/disable the glowbar?

I tried deleting `~/.local/share/plasma/desktoptheme/cherry/widgets/glowbar.svg` but the glowbar turned blue instead.

![image](https://github.com/nullxception/cherry-kde/assets/96933100/92de42e8-8a60-4a53-a8fc-dad2b75e1813)

**Comment by nullxception** [comment]
It's come from Screen edge.
There's multiple way to "get rid" of that glowing things:
- Disable the effect completely on System settings > Workspace behavior > Desktop effect > Screen edge.
- or, right click on the panel, enter edit mode > more options > change visibility to any other else than "windows can cover"
- or better way, use latte dock for better customization
